# Generated by Django 4.2.6 on 2024-04-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dispenser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispenser",
            name="heater_cycle_time",
            field=models.IntegerField(default=0),
        ),
    ]
