# Generated by Django 4.2.6 on 2024-05-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dispenser", "0002_dispenser_heater_cycle_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkdispensingprocess",
            name="dispenser_name",
            field=models.CharField(default="Tap-A", max_length=50),
        ),
    ]
