# Generated by Django 4.2.6 on 2024-06-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dispenser", "0004_alter_dispenser_dispense_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendingmachine",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendingmachine",
            name="pin_code",
            field=models.CharField(default="123456", max_length=6),
        ),
    ]
