# Generated by Django 4.2.6 on 2024-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0005_vendingmachine_is_locked_vendingmachine_pin_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrinkDispensingProcess',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='price_medium',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='volume_medium',
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='drink_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=10),
        ),
    ]
