# Generated by Django 4.2.6 on 2024-06-22 02:35

import dispenser.models
import dispenser.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0007_remove_dispenser_cleaner_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('cleaning', 'Cleaning'), ('serving', 'Operating'), ('error', 'Error'), ('setup', 'Setup')], default='idle', help_text='The status of the vending machine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='The background color of the display.', max_length=7),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='background_image',
            field=models.ImageField(blank=True, help_text='The background image of the display.', null=True, upload_to=dispenser.models.machine_image_upload_path, validators=[dispenser.validators.validate_machine_image_size, dispenser.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='font_name',
            field=models.CharField(default='Roboto Mono', help_text='The font name for the display.', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the machine is locked.'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='is_setting_up',
            field=models.BooleanField(default=False, help_text='Whether the machine is being set up.'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='name',
            field=models.CharField(help_text='The name of the vending machine.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='pin_code',
            field=models.CharField(default='123456', help_text='The pin code for unlocking the machine.', max_length=6),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='post_notifications',
            field=models.BooleanField(default=False, help_text='Whether to post notifications to the cloud server.'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store where the vending machine is located.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='dispenser.store'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='versionH',
            field=models.IntegerField(default=0, help_text='Hardware version'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='versionS',
            field=models.IntegerField(default=0, help_text='Software version'),
        ),
    ]
