# Generated by Django 4.2.6 on 2024-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0009_alter_vendingmachine_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='last_temperature_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='last_weight_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='temperature_notification_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='weight_notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
