# Generated by Django 5.0.4 on 2025-01-31 10:32

import dispenser.models
import dispenser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0010_dispenser_last_temperature_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='background_color',
            new_name='idle_background_color',
        ),
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='background_image',
            new_name='idle_background_image',
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='detection_timeout',
            field=models.IntegerField(default=10, help_text='The timeout for detecting the cup in seconds.'),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='dispensing_timeout',
            field=models.IntegerField(default=60, help_text='The timeout for dispensing the drink in seconds.'),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_button_font_style',
            field=models.CharField(default='Roboto Mono', help_text='The font name for the general buttons.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_button_text_color',
            field=models.CharField(default='#000000', help_text='The text color for the general buttons.', max_length=7),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_button_text_content',
            field=models.CharField(default='General Button', help_text='The text content for the general buttons.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_title_style',
            field=models.CharField(default='Roboto Mono', help_text='The font name for the general title.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_subtitle',
            field=models.CharField(default='Idle Subtitle', help_text='The subtitle of the idle page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_title',
            field=models.CharField(default='Idle Title', help_text='The title of the idle page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_title_font_color',
            field=models.CharField(default='#000000', help_text='The font color for the idle title.', max_length=7),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_title_font_style',
            field=models.CharField(default='Roboto Mono', help_text='The font name for the idle title.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='item_selection_title',
            field=models.CharField(default='Item Selection Title', help_text='The title of the item selection page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='item_size_title',
            field=models.CharField(default='Item Size Title', help_text='The title of the item size page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='payment_title',
            field=models.CharField(default='Payment Title', help_text='The title of the payment page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_background_image',
            field=models.ImageField(blank=True, help_text='The background image of the thank you page.', null=True, upload_to=dispenser.models.machine_image_upload_path, validators=[dispenser.validators.validate_machine_image_size, dispenser.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_exit_timeout',
            field=models.IntegerField(default=10, help_text='The timeout for exiting the thank you page in seconds.'),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_font_color',
            field=models.CharField(default='#000000', help_text='The font color for the thank you page.', max_length=7),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_font_style',
            field=models.CharField(default='Roboto Mono', help_text='The font name for the thank you page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_subtitle',
            field=models.CharField(default='Thank You Subtitle', help_text='The subtitle of the thank you page.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='thank_you_title',
            field=models.CharField(default='Thank You Title', help_text='The title of the thank you page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='weight_large',
            field=models.CharField(default='16oz', help_text='The weight of the large drink.', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='weight_small',
            field=models.CharField(default='12oz', help_text='The weight of the small drink.', max_length=20),
        ),
    ]
