# Generated by Django 5.0.4 on 2025-01-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0011_rename_background_color_vendingmachine_idle_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='font_name',
        ),
    ]
