# Generated by Django 5.0.4 on 2025-02-02 19:48

import dispenser.models
import dispenser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0012_remove_vendingmachine_font_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_video',
            field=models.FileField(blank=True, help_text='The video of the idle page.', null=True, upload_to=dispenser.models.machine_video_upload_path, validators=[dispenser.validators.validate_gif_size, dispenser.validators.validate_gif_file_extension]),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='idle_video_toggle',
            field=models.BooleanField(default=False, help_text='Whether to show the video on the idle page.'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='detection_timeout',
            field=models.IntegerField(default=30, help_text='The timeout for detecting the cup in seconds.'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='thank_you_exit_timeout',
            field=models.IntegerField(default=30, help_text='The timeout for exiting the thank you page in seconds.'),
        ),
    ]
