# Generated by Django 5.0.4 on 2025-02-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0013_vendingmachine_idle_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='idle_title_font_color',
            new_name='idle_font_color',
        ),
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='idle_title_font_style',
            new_name='idle_font_style',
        ),
    ]
