# Generated by Django 5.0.4 on 2025-02-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0014_rename_idle_title_font_color_vendingmachine_idle_font_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='general_title_style',
            new_name='general_title_font_style',
        ),
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='idle_font_color',
            new_name='idle_text_color',
        ),
        migrations.RenameField(
            model_name='vendingmachine',
            old_name='thank_you_font_color',
            new_name='thank_you_text_color',
        ),
    ]
