# Generated by Django 5.0.4 on 2025-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0015_rename_general_title_style_vendingmachine_general_title_font_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='general_button_text_content',
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_button_text_content_a',
            field=models.CharField(default='General Button A', help_text='The text content for the general button A.', max_length=100),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='general_button_text_content_b',
            field=models.CharField(default='General Button B', help_text='The text content for the general button B.', max_length=100),
        ),
    ]
